### ISSUE TITLE
Using I/O port as Input by QICK library

### ISSUE THREAD

**Issue by yyjun22** [openquantumhardware/qick#101]
I found that i can use Digital output I/O port by using QICK library.

But i also want to use Input function using QICK library.

I searched some QICK library detail, but i have no idea how to do that.

Do I have to use PYNQ library to use I/O input function?

thank you.

![image](https://user-images.githubusercontent.com/117146130/206945478-da241b80-5d7c-4965-a170-18de59816da7.png)

**Comment by meeg** [comment]
Digital inputs (to the tProc or to Python code) are not currently part of the QICK firmware or software. Could you give some idea of what you are trying to do?

**Comment by meeg** [comment]
Thanks, makes sense - however there is no built-in function for this in the QICK firmware. If you have some experience with FPGA programming it would be straightforward to write a simple logic block that counts pulses on a PMOD pin, and you would then be able to connect that block to PYNQ or the tProc.

**Comment by yyjun22** [comment]
Thanks, I understand.

I have another question.

I guess PMOD output pin is available in QICK library.

So I'm testing PMOD output pin to write 0 and 1 value referring to the homepage below.

https://pynq.readthedocs.io/en/v3.0.0/pynq_libraries/pmod.html

If I want to use PMODA or PMODB after booting qick library, do i have to make my own PMOD ip?
Because when i try to use "from pynq.overlays.base import BaseOverlay" which is from the homepage above, there's an error.

![image](https://user-images.githubusercontent.com/117146130/211960365-58961443-bb8b-4bce-8f5f-20a2535efa25.png)

**Comment by meeg** [comment]
The PYNQ "base overlay" you're looking at is a different firmware image. You can't have that loaded in the FPGA at the same time as the QICK firmware. If you just need to drive PMOD pins and you don't care about the RF DACs or ADCs, you could use the base overlay.

QICK does support PMOD output, but not using the PYNQ libraries. You would use https://qick-docs.readthedocs.io/en/latest/_autosummary/qick.qick_asm.html#qick.qick_asm.QickProgram.trigger as part of your QICK program.
