### ISSUE TITLE
Multiplexed readout with ZCU111

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [openquantumhardware/qick#118]
Hi @meeg , I am using the bitstream qick_111_rfbv1_mux.bit for multiplexing the readout but I have some doubts. 

I am doing the readout of three qubits at frequencies around 7000, 7200, and 7400 MHz.  So I am using a local oscillator set at 7.5 GHz and setting the pulse frequencies  (and the rest of the config) at

```
config = {
    'res_ch': 6,
    'ro_chs': [0,1,2],
    'nqz': 1,
    'mixer_freq': 1000,
    'pulse_freqs': [-500, -300, -100],
    'pulse_gains': [1.0, 1.0, 1.0],
    'pulse_style': 'const',
    'adc_trig_offset': 0.2,
    'length': 2,
    'readout_padding': 0.2,
    'relax_delay': 1,
    'reps': 1,
    'soft_avgs': 100
}
```
But I do not understand the parameter 'mixer_freq' as we use an external local oscillator. Besides some unit has changed (i.e.  'adc_trig_offset' now looks in mu_sec instead of clock tics), true?

Can you see anything wrong in this config?

Thank you

**Comment by meeg** [comment]
`mixer_freq` refers to a digital upconverter that is inside the FPGA logic (only for the mux and int4 generators). This frequency will be added to the `pulse_freqs` you have defined (in other words, the DAC will really generate `[500, 700, 900]`), and if you link a readout channel to this generator the readout will account for the mixer_freq (in other words, you should set `freq=-500` in `declare_readout()` to read out the first tone). It is independent of any analog mixer you may have off-board - in a typical setup where you use the same LO to mix up and mix down, there is no reason the QICK needs to know the LO frequency, right? Probably we could improve the description in https://qick-docs.readthedocs.io/en/latest/_autosummary/qick.qick_asm.html#qick.qick_asm.QickProgram.declare_gen.

Yes, the program you are using probably defines `adc_trig_offset` in units of us. You should look inside the program code (always good to read and understand the example code) and you will probably find a `us2cycles()` that converts this to ticks.
