### ISSUE TITLE
Potential bug using freq2reg_adc to assign adc frequency

### ISSUE THREAD

**Issue by Cameron-Spence-Riverlane** [openquantumhardware/qick#134]
Hi again,

I am attempting to run a simple pulse using an `axis_readout_v3` adc; to configure the adc I think I need to use `set_readout_registers`? However when compiling a program this way, the frequency appears to be incorrectly set:

```
// Program

        regwi 2, $11, 7267214222;               //freq = 29068856888
        bitwi 2, $11, $11 << 2;
        regwi 2, $15, 524388;                   //mode | outsel = 0b01000 | length = 100
```

leading to an error:

```
RuntimeError: Immediate values are only 31 bits 7267214222 > 2**31
```

```
self.declare_readout(ch=ch, length=cfg["readout_length"])
freq_ro = self.freq2reg_adc(cfg["pulse_freq"],ro_ch=ch,gen_ch=res_ch)
print(freq_ro)
self.set_readout_registers(ch=ch, freq=freq_ro, length=cfg["readout_length"],
                           mode='oneshot', outsel='product', phrst=1)
>> freq_ro = 29068856888
```

It seems that either the frequency register value is incorrectly calculated by `freq2reg_adc` (should be 31-bit? here `freq_ro` is > 2**31), or is being incorrectly translated to the `regwi` instruction.

Using freq2reg instead gives: 

```
>> freq_ro = 2972246926
```

Which compiles correctly, but I need it to sync to the output.

For reference, the frequency I am attempting to translate is 4990 MHz.

**Comment by meeg** [comment]
Thanks, you are right - fixed in #135.
