### ISSUE TITLE
External trigger via PMOD 

### ISSUE THREAD

**Issue by sebastianhorvath** [openquantumhardware/qick#137]
I've run into an issue using an external trigger input to flag experimental conditions to the tproc during executing using firmware 2023-03-23_216_testphase_q3diamond. Reading tproc input 3 returns that all four pins are high, irrespective of the input state. 

In the past I've also had a problem starting the tproc via an external trigger. We ended up resolving this by adding an external pull down resistor to the PMOD input. Unfortunately this didn't help here, and the value I read for tproc input 3 is 1111 even with a pull down resistor. 

```
prog = QickProgram(soccfg)

prog.synci(1000)
prog.memri(0, 1, 1)
prog.mathi(0, 1, 1, "+", 1)
prog.memwi(0, 1, 1)
prog.waiti(0, prog.us2cycles(5))
prog.read(3, 0, 'lower', 2)
prog.read(3, 0, 'upper', 3)
prog.memwi(0, 2, 2)
prog.synci(1000)
prog.waiti(0, 1000)
prog.end()

prog.load_program(soc, reset=True)

soc.tproc.single_write(addr=1, data=0)
soc.tproc.single_write(addr=2, data=0)

t0 = time.time() 
soc.start_src("external")

counts = np.int32(soc.tproc.single_read(addr=1))
trg_word_lower = np.int32(soc.tproc.single_read(addr=2))
trg_word_upper = np.int32(soc.tproc.single_read(addr=3))

print("%i counts in %i seconds" % (counts, time.time() - t0))
print("trigger, lower 32 bit word: %i, upper 32 bit word: %i" % (trg_word_lower, trg_word_upper))
```

I've also tried to use one of these PMOD level shifters to make sure the input levels and ground are matched to the ZCU216 board: 
https://digilent.com/shop/pmod-lvlshft-logic-level-shifter/

These work fine for external triggering (with the addition of a pull down resistor on the ZCU216 side). 

As always, thanks for all the help!

**Comment by meeg** [comment]
Looks OK to me? I changed your code a bit as follows (the only important change is that I am using internal start, not external start):
```
prog = QickProgram(soccfg)
prog.read(3, 0, 'lower', 2)
prog.read(3, 0, 'upper', 3)
prog.memwi(0, 2, 2)
prog.memwi(0, 3, 3)
prog.memri(0, 1, 1)
prog.mathi(0, 1, 1, "+", 1)
prog.memwi(0, 1, 1) # write count after writing data so we're sure the data has been written
prog.end()

prog.load_program(soc, reset=True)

soc.tproc.single_write(addr=1, data=0)
soc.tproc.single_write(addr=2, data=0)

t0 = time.time() 
# soc.start_src("external")
soc.start_src("internal")
soc.tproc.start()
time.sleep(0.01)

counts = np.int32(soc.tproc.single_read(addr=1))
trg_word_lower = np.int32(soc.tproc.single_read(addr=2))
trg_word_upper = np.int32(soc.tproc.single_read(addr=3))

print("%i counts in %i seconds" % (counts, time.time() - t0))
print("trigger, lower 32 bit word: %i, upper 32 bit word: %i" % (trg_word_lower, trg_word_upper))
```

If I don't connect anything, the result is 15, like you see - these inputs must float up when left open. If I tie PMOD1_7 to ground as below, I get 7, which is what I would expect.
![image](https://user-images.githubusercontent.com/905012/232137861-6242e769-4faa-4ae7-9b37-a665237c3875.png)

**Comment by sebastianhorvath** [comment]
Ah thank you, that's super helpful! 

It was a silly mistake on my part: I was referring to the pin numbers specified on the silk screen of the ZCU216 board/PMOD level shifter, but your picture clarified that these are not the same as the PMOD pin numbers! Therefore, my pulldown resistor was actually on data pin 3, and pins 4-7 were all high. 

I've done a bit of testing with quite a range of trigger lengths and repetition rates and its all working.

**Comment by meeg** [comment]
Great! Blame Xilinx.

Posting the pinout and buffer circuit in case I need to refer to this in the future.

![image](https://user-images.githubusercontent.com/905012/232342184-dcadc0b7-57c5-4cfc-a6d1-d53ad2a2ae95.png)
