### ISSUE TITLE
Behaviour not expected in the reconstruction of signals by the DACs on a ZCU111

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [openquantumhardware/qick#143]
Hi Sho

We are trying to control some qubits with frequencies very close to fs = 6.1 Gsps. We have chosen nyquist zone 2 and we suppose we are using mix mode reconstruction. The frequency response for this type of reconstruction is in theory like this

![mixModeReconstruction](https://github.com/openquantumhardware/qick/assets/9057076/19ce3b4d-7c6a-4449-9ef6-49cca63644ac)

so next to the fs we should get a pretty good signal.

But, we have computed the frequency response experimentally and we get a frequency response like this 

![boardResponse](https://github.com/openquantumhardware/qick/assets/9057076/4cf71a5a-c6e4-4dfc-a692-5067c0df476c)

The shapes are similar but there is a factor 2 difference and looks like the fs is just half of the supposed fs. So we can not send anything close to fs=6.1 Gsps

Hope I was clear enough. Any idea about why we are not getting the theoretical response?

Salut
Javi

**Comment by meeg** [comment]
Hi, sorry for the delay. I think you are forgetting about aliasing. When you request a tone at frequency f, the DAC always generates all of its Nyquist images (f, fs_DAC-f, fs_DAC+f, etc.). When you do a readout, the ADC cannot distinguish between its Nyquist images (f, fs_ADC-f, fs_ADC+f, etc.). For the standard ZCU111 firmware, fs_DAC = 2*fs_ADC. This has good properties (the DAC and ADC fabric clocks are the same) but it also means that all DAC Nyquist images for a given frequency are also ADC Nyquist images, and when you measure at frequency f you will really get the sum of f, fs_DAC-f, etc.

Of course the analog responses of the DAC, ADC, and signal path (baluns, etc.) are also involved.

**Comment by JavierSerranoGarcia** [comment]
Thank you, Sho for the response. I do not think we have any problem with aliasing or associated issues. Still I do not understand that behavior but things are working ok now.

Cheers
Javi

**Comment by meeg** [comment]
I hope this makes my point?
```
fs = 6144
x = np.linspace(0, 1.5*fs, 1001)

def transfer_normal(x):
    return np.sinc(x/fs)

def transfer_mixmode(x):
    return (np.pi*x/(2*fs))*np.sinc(x/(2*fs))**2

plt.semilogy(x, transfer_normal(x)**2, label='normal, no aliasing')
plt.semilogy(x, transfer_mixmode(x)**2, label='mix-mode, no aliasing')

plt.semilogy(x, transfer_normal(x)**2 + transfer_normal(fs-x)**2, label='normal, aliasing')
plt.semilogy(x, transfer_mixmode(x)**2 + transfer_mixmode(fs-x)**2, label='mix-mode, aliasing')

plt.ylim(1e-2,1)
plt.legend()
```
![image](https://github.com/openquantumhardware/qick/assets/905012/629b0bfd-cce3-4e24-8418-af6a10ec04eb)

**Comment by JavierSerranoGarcia** [comment]
Thank you very much for the explanation. The frequency responses you plotted match the experimental results we got and the sampling theory so that part is clear. What we did not consider properly was the balum response which is much more important than we thought.

Thank you again.
