### ISSUE TITLE
Variable phase in ZCU216

### ISSUE THREAD

**Issue by rodolfocarobene** [openquantumhardware/qick#164]
As @JavierSerranoGarcia was saying in #163, we just started testing the ZCU216 and we are encountering, as usual, some issues. 
Here I have a problem in a classification experiment, that may be related to some firmware differences since everything works as expected both for the rfsoc4x2 and the zcu111 (same code and same qubit) but not for the zcu216.

 I expect something like this (rfsoc4x2 result)
<img src="https://github.com/openquantumhardware/qick/assets/74607088/e451aad0-7b0e-41bc-bc67-e4b27c3abf74" width="300" height="280" />

While the result with the ZCU216 is
<img src="https://github.com/openquantumhardware/qick/assets/74607088/e9d8305b-0cba-41c0-8a0e-22376b7e9ea0" width="300" height="250" />
Other than being a nice-looking plot, this clearly doesn't make much sense.
It seems that there is a "running phase" during the experiment... is this something expected for the standard zcu216 firmware?
Eventually, is it avoidable?

Thank you in advance for the help and all the work!

**Comment by meeg** [comment]
This is not expected, the three standard firmwares all work identically in this regard.

Maybe you have a problem with the frequency matching between the readout and generator, as explained in https://github.com/openquantumhardware/qick/blob/main/qick_demos/00_Send_receive_pulse.ipynb.
