### ISSUE TITLE
Can DAC228_T0_CH3 be used?

### ISSUE THREAD

**Issue by zhizhenzhong** [openquantumhardware/qick#167]
HI there,

I find out that for the 7DDAC channels of QICK, you are using 3 DACs of DAC228_T0 (CH0, CH1, CH2), while leaving CH3 not connected? Why is this? Can this channel be connected? Thanks!

**Comment by meeg** [comment]
With the current architecture, the maximum number of DAC outputs from the tProcessor is 7 - see also #156.

If you want to disconnect some other channel so you can use this one, you would need to modify and recompile the firmware.
