### ISSUE TITLE
the link to gerber files is broken in qick/hardware/README.md

### ISSUE THREAD

**Issue by ikd-sci** [openquantumhardware/qick#177]
The Google Drive link in:
https://github.com/openquantumhardware/qick/blob/main/hardware/README.md?plain=1#L5
is broken

**Comment by sarafs1926** [comment]
Thanks for writing, sorry for the broken link. I just committed a new link, which should work. https://github.com/openquantumhardware/qick/commit/1ff55f73a6137673b63b7cf77eb96b9183bc0533

**Comment by ikd-sci** [comment]
Thanks!
