### ISSUE TITLE
timming-violation for both zcu111 and zcu216 in 87895db

### ISSUE THREAD

**Issue by CCvitaminHsieh** [openquantumhardware/qick#190]
Hi,

We downloaded your repo (87895db) and run implementation for both zcu111 (proj_111.tcl) and zcu216 (proj_216.tcl) and we encountered timing violation in both cas: 

![216-timming-violation](https://github.com/openquantumhardware/qick/assets/37689294/972ae1bc-a34e-4a57-8374-873febf05978)

![111-timming-violation](https://github.com/openquantumhardware/qick/assets/37689294/192b215c-061b-4a2f-aa9e-0527d2706b29)

The vivado version we are using is 2022.1.

**Comment by meeg** [comment]
Sorry for the delay, but this took some time:

When I generated the bitstreams from these projects originally, they passed timing. In response to your question I recreated and reran the projects, and now I see timing violations, but more severe than what you see. My suspicion is that this is related to the OS upgrade I ran on my PC in the interim (from Debian 11 to Debian 12); Vivado timing closure is supposed to be deterministic with respect to repeated runs, but not with respect to OS versions (https://support.xilinx.com/s/article/61599).

However I was able to get both projects to pass timing by changing the implementation strategy to Performance_Explore. So hopefully this will also work for you.

**Comment by CCvitaminHsieh** [comment]
Thanks for your reply.

However, even if I changed the implementation strategy to "Performance_Explore (Vivado Implement 2022)", I still got "Failed Timing" as shown in the image below.
![圖片](https://github.com/openquantumhardware/qick/assets/37689294/b9b61441-7daa-4a05-81e2-9257b2b24cb7)
![圖片](https://github.com/openquantumhardware/qick/assets/37689294/cec4918c-3cb6-4066-b127-467c221e76e0)

![圖片](https://github.com/openquantumhardware/qick/assets/37689294/39bc8757-c89f-4bb9-9e87-9141954d15c8)

I encountered a 'timing violation' while running on Windows 10 22H2. Perhaps I could try changing the operating system to Debian or another Linux distribution to see if it resolves this issue.

**Comment by meeg** [comment]
For what it's worth - if your worst negative slack is 12-13 ps like in your original screenshots, we think that's fine. Our firmware designer says anything under 50-60 ps is not something to worry about.

**Comment by CCvitaminHsieh** [comment]
Ok. Thanks!

**Comment by CCvitaminHsieh** [comment]
Ok. Thanks!
