### ISSUE TITLE
Unable to send a number with DAC and receive a number with ADC in a deterministic manner

### ISSUE THREAD

**Issue by lucyfan7266** [openquantumhardware/qick#214]
![plot_pulse](https://github.com/openquantumhardware/qick/assets/42194534/7857241b-cc6a-4cf8-bac9-a716a9d9945a)
![setup](https://github.com/openquantumhardware/qick/assets/42194534/035ac655-09aa-451d-835d-bd541b487d0d)
Hi team,

If using DAC sending a pulse to ADC with a loopback setup, do you know how to fix the number? For example, if choose pulse_gain as 500, I can get readout amplitude 3.5. But is there a way to deterministically control the amplitude, e.g. send 3.5 and get 3.5. Thanks!

**Comment by meeg** [comment]
No, you would need to calibrate that yourself for your specific frequency, choice of baluns, and cable losses.
