### ISSUE TITLE
changed ADC port in tcl but unable to measure meaningful data in readout

### ISSUE THREAD

**Issue by lucyfan7266** [openquantumhardware/qick#217]
![changed_port](https://github.com/openquantumhardware/qick/assets/42194534/679b6374-0392-4d29-8b27-3da88c54651c)
![224](https://github.com/openquantumhardware/qick/assets/42194534/27417bf9-e08d-4dfb-9c58-96b025326afd)
I changed the port in tcl and it printed the port 226 is functioning. But when I loop back from DAC to the right enabled ADC, it cannot get the right result in the measurement.

How can I verify that the port is really switched? Can you please suggest

**Comment by meeg** [comment]
Duplicate of #218
