### ISSUE TITLE
Read photodetector output -> ADC with the right input power and pulse gain

### ISSUE THREAD

**Issue by lucyfan7266** [openquantumhardware/qick#219]
Hi team,

I currently used qick package to control the FPGA Xilinx ZCU111. From DAC, I connected to LMH5401 back-to-back differential amplifiers and to MAX4444 evaluation kit to single output. This single output is applied as RF control in optical setup, laser-fiber-modulator-photodetector. The the photodetector is connected to LMH5401 with 50 Ohm single input, and read to ADC 226 ports.

I currently supply both LMH5401 amplifiers in DAC and ADC ends with 2.5V. This should work according to datasheets. But in another issue you mentioned we should supply ADC with 1.2 V. I know it is perhaps to improve data clip in the high amplitudes. But for now I stay with 2.5V to agree with datasheet.

My current setup is rather difficult to read meaningful output from ADC port. If I send 4 pulses and receive pulses, most of times I got the noise readout. Only a few times I get clear pulses with 2dBm optical power and pulse_gain 12000 and bias control of modulator at specific voltages. This type of trial experiments is not guranteed to succeed everytime and I wish to know how to read photodetector output from ADC port correctly. I have ruled out the electronics connection or optical device problems.

Thank you.
![noise](https://github.com/openquantumhardware/qick/assets/42194534/29bf71f3-a983-4aa5-ba62-9234ad2ded92)
![pulse](https://github.com/openquantumhardware/qick/assets/42194534/28e4f917-0cd9-4c74-9121-032f150f6ec8)

Thank you.

**Comment by meeg** [comment]
What datasheet are you looking at which says 2.5 V is correct for the common-mode voltage of signals going into the ADC?

The Xilinx datasheets (linked in #81 and #218) say 1.2 V or 1.25 V, for example in this figure from PG269:
![image](https://github.com/openquantumhardware/qick/assets/905012/5cda0fc8-ba4c-4894-a2d1-f500a6b14b4f)

At 2.5 V, you are even exceeding the absolute maximum $V_{ADC\\_VIN}$ (https://docs.xilinx.com/r/en-US/ds926-zynq-ultrascale-plus-rfsoc/Absolute-Maximum-Ratings) and could be damaging the ADC.

By the way - could you please give some general information on what you're trying to do with the QICK? It will be easier for us to support you if we understand how your needs relate to those of the rest of the QICK community.
