### ISSUE TITLE
use a machine learning training algorithm from a different FPGA

### ISSUE THREAD

**Issue by lucyfan7266** [openquantumhardware/qick#221]
Hi team,

I try to run MNIST inference an training with ZCU111 board. I found code from another [ZipML](https://github.com/fpgasystems/ZipML-PYNQ/) repo, my current ZCU111 board has installed qick, could you inspire me how to write a code for training and inference in MNIST?
Thank you.
![logo](https://github.com/openquantumhardware/qick/assets/42194534/2f985d11-d1d1-4ac7-b02b-54d0725833be)

**Comment by meeg** [comment]
Sorry, but ZipML seems to be software and firmware for the PYNQ-Z1 board. The only thing in common with QICK is the PYNQ OS. You would need to port the ZipML firmware to the ZCU111 and probably also make adjustments to the software; if you wanted to use ZipML functionality with QICK you would need to combine the two firmware designs.

**Comment by lucyfan7266** [comment]
Thank you. This is a reasonable solution! But I wanted to know, if I have implemented MNIST inference with ZCU111, can I use the training method in ZipML to update the MNIST training? Sorry I need some guidances.

**Comment by meeg** [comment]
I don't know, and I don't see the connection to QICK. I can't help.
