### ISSUE TITLE
Can't read 4x2 metadata with 0.2.287

### ISSUE THREAD

**Issue by i-am-mounce** [openquantumhardware/qick#288]
I'm stuck in a loop updating QICK-DAWG with some compatibility issues:

1. With version 0.2.160 I'm having issues with Pyro and somehow sending over np.int64 and float64's being an issue.  I think this is fixed in some later version of QICK. 
2. With 0.2.287 I'm getting an error that QickSoc() cannot even read the as provided RFSoC4x2 metadata.

**Comment by meeg** [comment]
1. Yes, I think #273 fixed this (though the fix is pretty ugly).
2. Will check on this. Are you seeing this with your firmware that has axis_avg_buffer:1.1, or is it also happening with the standard 4x2 firmware?

**Comment by i-am-mounce** [comment]
Seems standard firmware. I actually didn’t have an issue with axisaveragebuffer1.1

**Comment by meeg** [comment]
Can't reproduce on 0.2.287 and both standard and buf1.1 4x2 firmwares - I tried both with and without Pyro. This fails for you, right?
```
from qick import *
soc = QickSoc()
# soc = QickSoc("/home/xilinx/jupyter_notebooks/fw/2024-06-14_4x2_commonclk-4pt9/qick_4x2.bit")
soccfg = soc
print(soccfg)
```

**Comment by i-am-mounce** [comment]
Yes. That and default firmware. Let me do a fresh pynq image and try again. Maybe I screwed something up

**Comment by i-am-mounce** [comment]
Ok, fresh pynq image and qick install worked. Upgrading to 0.2.287 now, then i'll make a pull request for the photon counting!
