### ISSUE TITLE
Maximum ADC and DAC Sampling Rates

### ISSUE THREAD

**Issue by jramsey123** [openquantumhardware/qick#59]
What're the maximum sampling rates that have been run through the ZCU216 ADC and DAC with a QICK application?  With my ZCU208 work, I'd like to run the ADC's and DAC's at the highest possible sampling rates, which are 5GSPS for the ADCs and 10GSPS for the DACs.

**Comment by meeg** [comment]
We have a QICK firmware in use that runs the ADCs at 2.45G and some of the DACs at 9.58G, so we are pretty close to the max speeds for the ZCU216. Those DACs use the same signal generator block as the standard firmware.

**Comment by jramsey123** [comment]
@meeg 

Thank you for the quick response.  I've another question I'll ask in a different thread.
