### ISSUE TITLE
Running Qick/PYNQ without root privileges on a RFSoC4x2

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [openquantumhardware/qick#97]
We would like to install SLURM on the board to run Qick experiments but we are worried about having to do it as root. We know it is a Pynq limitation ([see here](https://discuss.pynq.io/t/pynq-overlay-without-root-privileges/212)).

Do you know if there is any recent solution to this issue?

**Comment by meeg** [comment]
Correct, it's not possible and is not likely to change. We've asked Xilinx.

**Comment by JavierSerranoGarcia** [comment]
Thank you for your fast reply.
